name: Testing : Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: dwt.tex
      - name: Upload Latex PDF File
        uses: actions/upload-artifact@v2
        with:
          name: DWT
          path: dwt.pdf
